apiVersion: v1
kind: Secret
metadata:
  name: notification-secret
stringData:
  GMAIL_ADDRESS: "taranpreetbatra1@gmail.com" #enter your email to get the id
  GMAIL_PASSWORD: "ujth xhwu mmah cqhz"
type: Opaque

# Passw0rd@1234